### ISSUE TITLE
Create Models/Migrations for revoked filings and 990N Data

### ISSUE THREAD

**Issue by Grantimus9** [grantmnelson/charityapi#6]
`rails g migration name_of_migration`, or `rails g model model_name` to make the models. 

Part 2: Make sure the references belongs_to and has_many are correct for each model-to-model relationship so far.

**Comment by yusufameri** [comment]
I made the models but the I think I will need some help confirming the "part 2" part

**Comment by Grantimus9** [comment]
Nice.
